name: Data Pipeline

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd my-pipeline
          pip install -r requirements.txt

      - name: Run pipeline script
        run: |
          cd my-pipeline
          python pipeline.py

      - name: Commit and push results
        run: |
          cd my-pipeline
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results.csv clean_data.csv raw_data.csv || true
          git commit -m "Update results from pipeline run [skip ci]" || echo "No changes to commit"
          git push
